version: '3'

services:
    bot:
        container_name: cubebot
        image: askador/cubebot:1.0
        build:
            context: .
        env_file: .env
        restart: unless-stopped
        depends_on:
            - postgresql
            - influxdb
        volumes:
            - /home/cubebot_data/:/cubebot

    postgresql:
        container_name: postgresql
        image: postgres:14.1
        restart: always
        ports:
            - '5432:5432'
        volumes:
            - /home/cubebot_data/pg_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: cubebot
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d cubebot"]
            interval: 10s
            timeout: 5s
            retries: 5

    influxdb:
        image: influxdb:1.8-alpine
        container_name: influxdb
        restart: always
        ports:
            - '8086:8086'
        # env_file: .env
        volumes:
            - /home/cubebot_data/influxdb_data:/var/lib/influxdb
        environment:
            INFLUXDB_DB: grafana
            INFLUXDB_USER: grafana
            INFLUXDB_USER_PASSWORD: password



volumes:
    influxdb_data:
    pg_data:
    cubebot_data: