"""update columns types

Revision ID: 268ffc0d4d8a
Revises: 0d6741ccbed1
Create Date: 2022-01-27 01:38:17.440888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268ffc0d4d8a'
down_revision = '0d6741ccbed1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats_logs', 'chat_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.alter_column('chats_logs', 'logs',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chats_logs', 'logs',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('chats_logs', 'chat_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###
