"""server_default

Revision ID: a78389aae547
Revises: 268ffc0d4d8a
Create Date: 2022-01-27 01:55:04.973752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a78389aae547'
down_revision = '268ffc0d4d8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("players", "money", server_default='1000')
    op.alter_column("players", "plays_amount", server_default='0')
    op.alter_column("players", "won", server_default='0')
    op.alter_column("players", "loss", server_default='0')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("players", "money", server_deafult=sa.sql.expression.null())
    op.alter_column("players", "plays_amount", server_default=sa.sql.expression.null())
    op.alter_column("players", "won", server_default=sa.sql.expression.null())
    op.alter_column("players", "loss", server_default=sa.sql.expression.null())
    # ### end Alembic commands ###
