"""fullname lenght

Revision ID: e3b54868e668
Revises: a78389aae547
Create Date: 2022-01-27 15:06:21.744079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b54868e668'
down_revision = 'a78389aae547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("players", "fullname", 
                type_=sa.String(65),
                nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("players", "fullname", 
                type_=sa.String,
                nullable=False
    )
    # ### end Alembic commands ###
